"""Small deterministic SQLite migration runner for the repository bootstrap.

Reliability contract (round 3):
- empty data root initializes through the full packaged migration chain;
- an applied migration whose SQL changed since it was recorded FAILS CLOSED
  (checksum mismatch), so a modified historical migration can never silently
  re-run or mask drift;
- migration failure is atomic: each migration runs inside one transaction and
  rolls back on error;
- the runner is idempotent across restarts (version + checksum recorded).
"""

from __future__ import annotations

import hashlib
import sqlite3
from dataclasses import dataclass
from datetime import UTC, datetime
from importlib.resources import files
from pathlib import Path


@dataclass(frozen=True, slots=True)
class MigrationResult:
    """Summary of one migration run."""

    database_path: Path
    applied_versions: tuple[str, ...]


class MigrationChecksumError(RuntimeError):
    """Raised when an already-applied migration changed since it was applied."""


def _sha256(sql: str) -> str:
    return hashlib.sha256(sql.encode("utf-8")).hexdigest()


def _migration_sources(migrations_dir: Path | None) -> tuple[tuple[str, str], ...]:
    if migrations_dir is not None:
        return tuple(
            sorted(
                (path.name, path.read_text(encoding="utf-8"))
                for path in migrations_dir.glob("*.sql")
            )
        )
    root = files("iris_memory.db.migrations")
    return tuple(
        sorted(
            (entry.name, entry.read_text(encoding="utf-8"))
            for entry in root.iterdir()
            if entry.name.endswith(".sql")
        )
    )


def _release_owned_checksums(migrations_dir: Path | None) -> dict[str, str]:
    """Load the release-owned migration checksum manifest. The manifest is
    generated by the maintainer and committed; the runner uses it to bless
    legacy empty checksums (never current disk bytes)."""
    if migrations_dir is not None:
        manifest_path = migrations_dir / "checksums.json"
        if not manifest_path.exists():
            return {}
        raw = manifest_path.read_text(encoding="utf-8")
    else:
        import json as _json
        from importlib.resources import files as _files

        target = _files("iris_memory.db.migrations").joinpath("checksums.json")
        if not target.is_file():
            return {}
        raw = target.read_text(encoding="utf-8")
    import json as _json

    try:
        manifest = _json.loads(raw)
    except ValueError as exc:
        raise MigrationChecksumError(f"invalid checksums manifest: {exc}") from exc
    checksums = manifest.get("checksums", {}) if isinstance(manifest, dict) else {}
    if not isinstance(checksums, dict):
        raise MigrationChecksumError("checksums manifest is missing 'checksums' object")
    return {str(k): str(v) for k, v in checksums.items()}


def _recorded_migrations(connection: sqlite3.Connection) -> dict[str, str]:
    """Return {version: checksum} for already-applied migrations. Tolerates
    databases where the checksum column does not exist yet (0004 adds it)."""
    columns = {
        row[1] for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
    }
    if "checksum" not in columns:
        return {
            str(row[0]): ""
            for row in connection.execute(
                "SELECT version FROM schema_migrations ORDER BY version"
            ).fetchall()
        }
    return {
        str(row[0]): str(row[1])
        for row in connection.execute(
            "SELECT version, checksum FROM schema_migrations ORDER BY version"
        ).fetchall()
    }


def apply_migrations(database_path: Path, *, migrations_dir: Path | None = None) -> MigrationResult:
    """Apply packaged SQL migrations exactly once, in filename order.

    - An empty data root initializes through every packaged migration.
    - A migration already recorded with a different checksum FAILS CLOSED.
    - Each migration commits atomically (BEGIN/COMMIT around all statements
      + the bookkeeping insert).
    - After applying, every recorded version is re-verified against the
      on-disk SQL so a historical modification cannot pass silently.
    """
    database_path.parent.mkdir(parents=True, exist_ok=True)
    applied: list[str] = []

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version TEXT PRIMARY KEY,
                applied_at TEXT NOT NULL,
                checksum TEXT NOT NULL DEFAULT ''
            )
            """
        )
        recorded = _recorded_migrations(connection)

        sources = _migration_sources(migrations_dir)
        source_versions = {name.removesuffix(".sql") for name, _ in sources}

        # M4 (review): a version recorded in the DB but absent from the
        # current source set is a deleted/renamed migration — fail closed.
        missing_sources = sorted(set(recorded) - source_versions)
        if missing_sources:
            raise MigrationChecksumError(
                "recorded migrations missing from source: " + ", ".join(missing_sources)
            )

        # M4 (review): pre-round-3 rows have checksum ''. Backfill ONLY from
        # the release-owned checksums manifest (db/migrations/checksums.json) —
        # never from whatever bytes are on disk today, which would bless
        # tampered history. A version with no release-owned checksum FAILS
        # CLOSED and requires an explicit audited migration.
        release_checksums = _release_owned_checksums(migrations_dir)
        backfilled_any = False
        for version, recorded_checksum in recorded.items():
            if recorded_checksum == "":
                release_checksum = release_checksums.get(version)
                if release_checksum is None:
                    raise MigrationChecksumError(
                        f"migration {version} has no release-owned checksum; "
                        "an explicit audited migration is required"
                    )
                # The checksum column may not exist until 0004 runs on a
                # legacy DB; update only when the column is present, and let
                # the post-apply verify pass catch any remaining empty rows.
                columns = {
                    row[1]
                    for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
                }
                if "checksum" in columns:
                    connection.execute(
                        "UPDATE schema_migrations SET checksum = ? WHERE version = ?",
                        (release_checksum, version),
                    )
                recorded[version] = release_checksum
                backfilled_any = True
        # Commit the standalone backfill so the per-migration BEGIN below
        # never collides with python sqlite3's implicit transaction.
        if backfilled_any:
            connection.commit()

        for migration_name, sql in sources:
            version = migration_name.removesuffix(".sql")
            checksum = _sha256(sql)
            if version in recorded:
                # Empty checksums were backfilled in the pass above; any
                # remaining non-empty mismatch is a real drift.
                recorded_checksum = recorded[version]
                if recorded_checksum != checksum:
                    raise MigrationChecksumError(
                        f"migration {version} changed after being applied "
                        f"(recorded {recorded_checksum}, current {checksum})"
                    )
                continue

            statements = [part.strip() for part in sql.split(";") if part.strip()]
            connection.execute("BEGIN")
            try:
                existing_columns = {
                    row[1]
                    for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
                }
                for statement in statements:
                    # 0004 adds the checksum column only if missing; for fresh
                    # databases the CREATE TABLE already has it, so the ALTER
                    # would fail. Skip idempotent ALTERs here.
                    if (
                        "ADD COLUMN" in statement.upper()
                        and "checksum" in statement.lower()
                        and "checksum" in existing_columns
                    ):
                        continue
                    connection.execute(statement)
                has_checksum_column = "checksum" in {
                    row[1]
                    for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
                }
                if has_checksum_column:
                    connection.execute(
                        "INSERT INTO schema_migrations(version, applied_at, checksum)"
                        " VALUES (?, ?, ?)",
                        (version, datetime.now(UTC).isoformat(), checksum),
                    )
                else:
                    connection.execute(
                        "INSERT INTO schema_migrations(version, applied_at) VALUES (?, ?)",
                        (version, datetime.now(UTC).isoformat()),
                    )
                connection.commit()
            except sqlite3.Error:
                connection.rollback()
                raise
            applied.append(version)
            recorded[version] = checksum

    return MigrationResult(database_path=database_path, applied_versions=tuple(applied))
