"""Small deterministic SQLite migration runner for the repository bootstrap.

Reliability contract (round 3):
- empty data root initializes through the full packaged migration chain;
- an applied migration whose SQL changed since it was recorded FAILS CLOSED
  (checksum mismatch), so a modified historical migration can never silently
  re-run or mask drift;
- migration failure is atomic: each migration runs inside one transaction and
  rolls back on error;
- the runner is idempotent across restarts (version + checksum recorded).
"""

from __future__ import annotations

import hashlib
import sqlite3
from dataclasses import dataclass
from datetime import UTC, datetime
from importlib.resources import files
from pathlib import Path


@dataclass(frozen=True, slots=True)
class MigrationResult:
    """Summary of one migration run."""

    database_path: Path
    applied_versions: tuple[str, ...]


class MigrationChecksumError(RuntimeError):
    """Raised when an already-applied migration changed since it was applied."""


def _sha256(sql: str) -> str:
    return hashlib.sha256(sql.encode("utf-8")).hexdigest()


def _migration_sources(migrations_dir: Path | None) -> tuple[tuple[str, str], ...]:
    if migrations_dir is not None:
        return tuple(
            sorted(
                (path.name, path.read_text(encoding="utf-8"))
                for path in migrations_dir.glob("*.sql")
            )
        )
    root = files("iris_memory.db.migrations")
    return tuple(
        sorted(
            (entry.name, entry.read_text(encoding="utf-8"))
            for entry in root.iterdir()
            if entry.name.endswith(".sql")
        )
    )


def _release_owned_checksums(migrations_dir: Path | None) -> dict[str, str]:
    """Load the release-owned migration checksum manifest. The manifest is
    generated by the maintainer and committed; the runner uses it to bless
    legacy empty checksums (never current disk bytes)."""
    if migrations_dir is not None:
        manifest_path = migrations_dir / "checksums.json"
        if not manifest_path.exists():
            return {}
        raw = manifest_path.read_text(encoding="utf-8")
    else:
        import json as _json
        from importlib.resources import files as _files

        target = _files("iris_memory.db.migrations").joinpath("checksums.json")
        if not target.is_file():
            return {}
        raw = target.read_text(encoding="utf-8")
    import json as _json

    try:
        manifest = _json.loads(raw)
    except ValueError as exc:
        raise MigrationChecksumError(f"invalid checksums manifest: {exc}") from exc
    checksums = manifest.get("checksums", {}) if isinstance(manifest, dict) else {}
    if not isinstance(checksums, dict):
        raise MigrationChecksumError("checksums manifest is missing 'checksums' object")
    return {str(k): str(v) for k, v in checksums.items()}


def _recorded_migrations(connection: sqlite3.Connection) -> dict[str, str]:
    """Return {version: checksum} for already-applied migrations. Tolerates
    databases where the checksum column does not exist yet (0004 adds it)."""
    columns = {
        row[1] for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
    }
    if "checksum" not in columns:
        return {
            str(row[0]): ""
            for row in connection.execute(
                "SELECT version FROM schema_migrations ORDER BY version"
            ).fetchall()
        }
    return {
        str(row[0]): str(row[1])
        for row in connection.execute(
            "SELECT version, checksum FROM schema_migrations ORDER BY version"
        ).fetchall()
    }


def apply_migrations(database_path: Path, *, migrations_dir: Path | None = None) -> MigrationResult:
    """Apply packaged SQL migrations exactly once, in filename order.

    - An empty data root initializes through every packaged migration.
    - A migration already recorded with a different checksum FAILS CLOSED.
    - Each migration commits atomically (BEGIN/COMMIT around all statements
      + the bookkeeping insert).
    - After applying, every recorded version is re-verified against the
      on-disk SQL so a historical modification cannot pass silently.
    """
    database_path.parent.mkdir(parents=True, exist_ok=True)
    applied: list[str] = []

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version TEXT PRIMARY KEY,
                applied_at TEXT NOT NULL,
                checksum TEXT NOT NULL DEFAULT ''
            )
            """
        )
        recorded = _recorded_migrations(connection)

        sources = _migration_sources(migrations_dir)
        source_versions = {name.removesuffix(".sql") for name, _ in sources}

        # M4 (review): a version recorded in the DB but absent from the
        # current source set is a deleted/renamed migration — fail closed.
        missing_sources = sorted(set(recorded) - source_versions)
        if missing_sources:
            raise MigrationChecksumError(
                "recorded migrations missing from source: " + ", ".join(missing_sources)
            )

        # review-pass-2 #4: BEFORE applying anything (including on a clean
        # database), the release-owned manifest must match the source set
        # EXACTLY — missing, extra, or hash-mismatched entries all fail
        # closed. The DB records always use the release-owned checksum, never
        # whatever bytes happen to be on disk.
        release_checksums = _release_owned_checksums(migrations_dir)
        release_versions = set(release_checksums)
        if release_versions != source_versions:
            missing = sorted(source_versions - release_versions)
            extra = sorted(release_versions - source_versions)
            problems = []
            if missing:
                problems.append(f"source without release checksum: {missing}")
            if extra:
                problems.append(f"release checksum without source: {extra}")
            raise MigrationChecksumError("release manifest mismatch: " + "; ".join(problems))
        source_by_version = {name.removesuffix(".sql"): sql for name, sql in sources}
        for version in sorted(source_versions):
            actual = _sha256(source_by_version[version])
            if release_checksums[version] != actual:
                raise MigrationChecksumError(
                    f"migration {version} bytes do not match its release-owned checksum"
                )

        # review-pass-2 #3 + review-pass-3 #1: pre-round-3 rows (checksum '')
        # that predate the checksum column are collected so they can be
        # backfilled from the release manifest; when the column does not exist
        # yet (0004 not applied) they are DEFERRED to the post-0004 pass,
        # which backfills EVERY empty row — including migrations applied
        # between 0003 and 0004 that were inserted without a checksum.
        deferred_backfill: list[tuple[str, str]] = []
        backfilled_any = False
        columns = {
            row[1] for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
        }
        has_checksum_column = "checksum" in columns
        for version, recorded_checksum in recorded.items():
            if recorded_checksum == "":
                release_checksum = release_checksums.get(version)
                if release_checksum is None:
                    raise MigrationChecksumError(
                        f"migration {version} has no release-owned checksum; "
                        "an explicit audited migration is required"
                    )
                if has_checksum_column:
                    connection.execute(
                        "UPDATE schema_migrations SET checksum = ? WHERE version = ?",
                        (release_checksum, version),
                    )
                    backfilled_any = True
                else:
                    deferred_backfill.append((version, release_checksum))
                recorded[version] = release_checksum
        # review-pass-4 #1: commit whenever a UPDATE actually ran — python
        # sqlite3 opens an implicit transaction on the first UPDATE, and the
        # in-memory `recorded` map is already populated with release checksums
        # so 'any(empty)' would be false and the explicit BEGIN in the
        # migration loop would collide with the open implicit transaction.
        if backfilled_any:
            connection.commit()

        for migration_name, sql in sources:
            version = migration_name.removesuffix(".sql")
            checksum = release_checksums[version]
            if version in recorded:
                # Legacy rows were backfilled above; any remaining non-empty
                # mismatch against the release-owned checksum is real drift.
                recorded_checksum = recorded[version]
                if recorded_checksum != "" and recorded_checksum != checksum:
                    raise MigrationChecksumError(
                        f"migration {version} changed after being applied "
                        f"(recorded {recorded_checksum}, current {checksum})"
                    )
                continue

            statements = [part.strip() for part in sql.split(";") if part.strip()]
            connection.execute("BEGIN")
            try:
                existing_columns = {
                    row[1]
                    for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
                }
                for statement in statements:
                    # 0004 adds the checksum column only if missing; for fresh
                    # databases the CREATE TABLE already has it, so the ALTER
                    # would fail. Skip idempotent ALTERs here.
                    if (
                        "ADD COLUMN" in statement.upper()
                        and "checksum" in statement.lower()
                        and "checksum" in existing_columns
                    ):
                        continue
                    connection.execute(statement)
                has_checksum_column_now = "checksum" in {
                    row[1]
                    for row in connection.execute("PRAGMA table_info(schema_migrations)").fetchall()
                }
                if has_checksum_column_now:
                    connection.execute(
                        "INSERT INTO schema_migrations(version, applied_at, checksum)"
                        " VALUES (?, ?, ?)",
                        (version, datetime.now(UTC).isoformat(), checksum),
                    )
                else:
                    connection.execute(
                        "INSERT INTO schema_migrations(version, applied_at) VALUES (?, ?)",
                        (version, datetime.now(UTC).isoformat()),
                    )
                connection.commit()
            except sqlite3.Error:
                connection.rollback()
                raise
            applied.append(version)
            recorded[version] = checksum

            # review-pass-2 #3 + review-pass-3 #1 + review-pass-4 #1: if this
            # migration introduced the checksum column (0004), UNCONDITIONALLY
            # backfill every row whose DB checksum is still '' in the SAME
            # transaction/run — the deferred legacy rows, migrations applied
            # just before 0004 (e.g. 0003) that were inserted without a
            # checksum, AND the 'zero recorded migrations' baseline (old
            # runner created the table, 0001-0003 apply in this run). The gate
            # is the DB empty-row query itself, never the in-memory `recorded`
            # map (which was pre-populated with release checksums) or the
            # deferred list. A single apply_migrations() therefore leaves ALL
            # historical checksums non-empty; a crash between the 0004 commit
            # and this backfill is deterministically completed by the next run.
            if version == "0004_checksum_metadata":
                # Backfill EVERY row whose DB checksum is still '' (the
                # deferred legacy rows AND migrations applied in this run
                # before the column existed, e.g. 0003). Read the DB value —
                # not the in-memory `recorded` map, which was pre-populated
                # with release checksums — so the FIRST run persists all of
                # them.
                connection.execute("BEGIN")
                try:
                    empty_rows = connection.execute(
                        "SELECT version FROM schema_migrations WHERE checksum = ''"
                    ).fetchall()
                    for (legacy_version,) in empty_rows:
                        release_checksum = release_checksums.get(legacy_version)
                        if release_checksum is None:
                            raise MigrationChecksumError(
                                f"migration {legacy_version} has no release-owned "
                                "checksum; an explicit audited migration is required"
                            )
                        connection.execute(
                            "UPDATE schema_migrations SET checksum = ? WHERE version = ?",
                            (release_checksum, legacy_version),
                        )
                        recorded[legacy_version] = release_checksum
                    connection.commit()
                except sqlite3.Error:
                    connection.rollback()
                    raise
                deferred_backfill = []

    return MigrationResult(database_path=database_path, applied_versions=tuple(applied))
